{% set name = "neuralforecast" %}
{% set version = "3.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eea25c7f4a885b56d2f2a96b1aebaa425da730f25b5176783018c5f62fc11b13

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
  run:
    - python
    - coreforecast >=0.0.6
    - fsspec
    - numpy >=1.21.6
    - pandas >=1.3.5
    - scipy
    - pytorch >=2.9.1
    - tornado >=6.5.5
    - pytorch-lightning >=2.0.0,<2.6.0
    # ray[train,tune]>=2.2.0
    - ray-train >=2.2.0
    - ray-tune >=2.2.0
    - optuna
    - utilsforecast >=0.2.3
  run_constrained:
    # spark
    - pyspark >=3.5
    - pyarrow >=23.0.1

test:
  source_files:
    - tests
  imports:
    - neuralforecast
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/Nixtla/neuralforecast/tree/main/
  summary: Deep Learning for Time Series Forecasting
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    State-of-the-art time series forecasting for PyTorch.

    `NeuralForecast` is a Python library for time series forecasting with 
    deep learning models. It includes *benchmark datasets*, *data-loading 
    utilities*, *evaluation functions*, statistical *tests*, univariate *model 
    benchmarks* and *SOTA* models implemented in PyTorch and PyTorchLightning.

    PyPI: [https://pypi.org/project/neuralforecast/](https://pypi.org/project/neuralforecast/)

  doc_url: https://nixtla.github.io/neuralforecast
  dev_url: https://github.com/Nixtla/neuralforecast

extra:
  recipe-maintainers:
    - sugatoray
    - cchallu
    - FedericoGarza
