{% set name = "neuralforecast" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/neuralforecast-{{ version }}.tar.gz
  sha256: c1084144a1c8009ac92ef5d1b9f9c2efa7c130685b080212dee0516153692dbf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<36]

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - numpy
    - pandas >=1.3.5
    - pytorch >=1.12.1
    - pytorch-lightning 1.9.3
    # - ray-tune 2.3.0

test:
  imports:
    - neuralforecast
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Nixtla/neuralforecast/tree/main/
  summary: Deep Learning for Time Series Forecasting
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    State-of-the-art time series forecasting for PyTorch.

    `NeuralForecast` is a Python library for time series forecasting with 
    deep learning models. It includes *benchmark datasets*, *data-loading 
    utilities*, *evaluation functions*, statistical *tests*, univariate *model 
    benchmarks* and *SOTA* models implemented in PyTorch and PyTorchLightning.

    PyPI: [https://pypi.org/project/neuralforecast/](https://pypi.org/project/neuralforecast/)

  doc_url: https://nixtla.github.io/neuralforecast
  dev_url: https://github.com/Nixtla/neuralforecast/tree/main/

extra:
  recipe-maintainers:
    - sugatoray
    - cchallu
    - FedericoGarza
